DROP POLICY IF EXISTS "admin_step_up_challenge_scope" ON "admin_step_up_challenge";
DROP POLICY IF EXISTS "admin_email_delivery_scope" ON "admin_email_delivery";
DROP POLICY IF EXISTS "platform_audit_event_scope" ON "platform_audit_event";
DROP POLICY IF EXISTS "platform_account_read_scope" ON "platform_account";
DROP POLICY IF EXISTS "platform_account_boundary" ON "platform_account";
DROP POLICY IF EXISTS "workspace_platform_boundary" ON "workspace";
DROP POLICY IF EXISTS "membership_platform_boundary" ON "membership";
DROP TRIGGER IF EXISTS "platform_session_guard" ON "session";
DROP FUNCTION IF EXISTS "app"."guard_platform_session_insert"();
DROP FUNCTION IF EXISTS "app"."lock_platform_session_user"(text);
DROP FUNCTION IF EXISTS "app"."assert_platform_session_allowed"(text);
DROP FUNCTION IF EXISTS "app"."platform_account_workspaces"(text);
DROP FUNCTION IF EXISTS "app"."platform_account_metadata"(text);
DROP FUNCTION IF EXISTS "app"."platform_role_for_user"(text);
DROP FUNCTION IF EXISTS "app"."platform_status_for_user"(text);
DROP FUNCTION IF EXISTS "app"."current_platform_role"();
DROP FUNCTION IF EXISTS "app"."claim_first_platform_admin"(text);
DROP TABLE IF EXISTS "admin_step_up_challenge";
DROP TABLE IF EXISTS "admin_email_delivery";
DROP TABLE IF EXISTS "platform_audit_event";
DROP TABLE IF EXISTS "platform_account";
DROP INDEX IF EXISTS "twoFactor_userId_idx";
DROP TABLE IF EXISTS "twoFactor";
ALTER TABLE "user" DROP COLUMN IF EXISTS "two_factor_enabled";
DROP ROLE IF EXISTS casei_platform_boundary;
